require("alextsagkas.packer")

require("alextsagkas.core.colorscheme")
require("alextsagkas.core.keymaps")
require("alextsagkas.core.options")

require("alextsagkas.plugins.lsp.lspconfig")
require("alextsagkas.plugins.lsp.lspsaga")
require("alextsagkas.plugins.lsp.mason")
require("alextsagkas.plugins.lsp.null-ls")

require("alextsagkas.plugins.autopairs")
require("alextsagkas.plugins.blankline")
require("alextsagkas.plugins.bufferline")
require("alextsagkas.plugins.colorizer")
require("alextsagkas.plugins.comment")
require("alextsagkas.plugins.copilot")
require("alextsagkas.plugins.fugitive")
require("alextsagkas.plugins.gitsings")
require("alextsagkas.plugins.harpoon")
require("alextsagkas.plugins.highlight-colors")
require("alextsagkas.plugins.lualine")
require("alextsagkas.plugins.markdown-preview")
require("alextsagkas.plugins.maximizer")
require("alextsagkas.plugins.noice")
require("alextsagkas.plugins.nvim-tree")
require("alextsagkas.plugins.nvim-cmp")
require("alextsagkas.plugins.tagbar")
require("alextsagkas.plugins.tailwindcss-colors")
require("alextsagkas.plugins.telescope")
require("alextsagkas.plugins.todo-comments")
require("alextsagkas.plugins.treesitter-context")
require("alextsagkas.plugins.treesitter")
require("alextsagkas.plugins.undotree")
require("alextsagkas.plugins.vimtex")
require("alextsagkas.plugins.zen-mode")
